@echo off
ML.EXE /c ../code/MATRIX.ASM /c ../code/TOOLS.ASM /c ../code/DOTSCAL.ASM ../code/ADD.ASM 
ML.exe /c ../code/MUL.ASM ../code/NEG.ASM ../code/STRINT.ASM
ML.EXE /c ../code/SUB.ASM ../code/TRANSP.ASM  
LIB.EXE LIB.LIB MATRIX.OBJ+TOOLS.OBJ+ADD.OBJ+DOTSCAL.OBJ+MUL.OBJ+NEG.OBJ+STRINT.OBJ+SUB.OBJ+TRANSP.OBJ  
ML.EXE MAIN.ASM
MAIN.EXE